### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by ChristopherMank** [biblequiz/BibleQuiz.com#538]
Hello,

First off let me say thank you for all the work you guys are doing on the website and new Coach's app. Love seeing how alive this has become. Second, we used the new Coach's app for our JBQ District Finals and was wondering what the proper forum is for feature requests. We have a couple we'd love to see incorporated in the future if they are not already on your backlog.

Thanks!

Christopher

**Comment by kevintgallo** [comment]
Thanks for connecting with us and sorry for the slow response.

I have made several updates based on some requests from our users, so please check out the new version. One of the big changes was to improve the online scoring integration by show the difference between your score and online score from the scorekeeper.

I am going to start using the google group I created and add you to as a way of informing folks when new features are released and discuss feature tradeoffs where appropriate.

For feature requests, we have been very informal.  You can send me an email, schedule a zoom or Teams call, or just write it up here.

**Comment by ChristopherMank** [comment]
Sounds great, thanks @kevintgallo ! I might add a few things here or send in email. The addition of Cannot Lose and quick unseat were on my list so glad you got those. The others we'd love to see are:

1. Copy seating from pervious round (for my team).
2. Customize the keyboard shortcuts, like how you advance to the next question. The Enter key was really nice for this versus now having to do a combination of keys. 
3. Easily create a dummy match not tied to any scoring for practice, demos, testing, etc.

**Comment by kevintgallo** [comment]
Great suggestions:
1. I will look into this as it is so common a scenario.  I wonder whether copy from previous or "my defaults" are better or simpler to setup.
2. This is tough as some keystrokes cannot be used as they are special keys for windows for edit field, cut and paste, scrolling, etc.  If enter worked then that was a bug as enter is used for lots of other functionality within edit field and such.  What would you like them to be?
3. The top issue for next year is creating ad hoc practice matches and generating questions and setting up quizzers.  You can do it now but it has degraded since my first attempt as I struggled with the right way to do it. I am planning to have a brainstorming meeting on this to think through the options and complexities.  For example, entering names every time is really hard and felt wrong as most of the names were already in the registration site.  So then I tried to create matches by selecting the church and setting the user name.  It seemed ok to me but without logging in we do not have all the information available to us and I was hoping to avoid a login.  We also would need to change the UX to show the questions rather than doing research and I would like to think that through again with some other users who can help shape the experience.

Are you using this for JBQ or TBQ or both?

**Comment by kevintgallo** [comment]
We would replicate the question generator in order to run the practice. At some point we are thinking we could just do the generation ourselves when you create the event.

I was thinking that I could have a save default/ restore default from the seating dialog so it takes up no additional UI and easy to discover.

Are you guys going to JBQ Nationals?  Would be great to chat there if you are.
________________________________

**Comment by ChristopherMank** [comment]
Replicating the question generator would be fantastic. It would also be nice to improve it as the current version is far from "random".  Agreed on the UI for seating.

Yes, we'll be at JBQ (and TBQ) Nationals. Let's plan to sync up. Thanks!
